### ISSUE TITLE
Update Header/Footer to accommodate smaller screen widths

### ISSUE THREAD

**Issue by katyasoup** [CDCgov/dibbs-query-connector#106]
## Description:

When viewing at smaller/mobile screen sizes, certain parts of the app don't resize appropriately. 

## Acceptance Criteria:

**Header:** Content has even padding/margin and dropdown menu retains full-screen styles. Also dropdown menu should not persist in an open state when navigating between pages.

**Footer:** Text stacks into two rows rather than overlapping

**Comment by fzhao99** [comment]
think I pulled out the grid display styling in the last PR that makes the sign in page content fill the full space between header / footer, so i put up a PR to fix that here!

https://github.com/CDCgov/dibbs-query-connector/pull/111
