### ISSUE TITLE
Fix Social Determinants of Health in Customize Query Screen

### ISSUE THREAD

**Issue by robertandremitchell** [CDCgov/dibbs-query-connector#52]
### Environment

occurs in local and production 
<img width="1214" alt="Screenshot 2024-10-23 at 3 08 36 PM" src="https://github.com/user-attachments/assets/0f2f48f5-27c6-4c93-890b-f15647c9cbc3">

### Description

Something has occurred that social determinants of health no longer populates codes. This means that users cannot actually customize the query.

### Impact

End users might want to modify or expect to be able to modify social determinants and will be unable to.

### Steps to Reproduce

1. Run `npm run dev`.
2. Navigate to `localhost:3000/query`.
3. Click `Fill Fields`.
4. Click `Search for Patient`.
5. Click `Hyper Unlucky`.
6. Select `Gather Social determinants of Health` in the dropdown.
7. Click `Customize Query`. 
8. Codes should populate.

### Expected Behavior

Codes should return.

**Comment by robertandremitchell** [comment]
do we actually want to remove this from the dropdown? I am not seeing anything in our current migrations to do this.

Moreover, in our new test workflow, we will always see Hyper Unlucky's social determinants regardless of whether we select. It seems kind of not needed unless we want to have some way to show it could be plausible to remove/modify what social determinants get displayed in the data. In which case, I think we will need to modify the migrations to add similar to what we do for newborn screening.

@DanielPaseltiner , curious your thoughts on if it makes more sense to remove from the dropdown or to build out the migrations to include a customize query for social determinants.

**Comment by bamader** [comment]
Yeah checking this out a bit more, I'm seeing a "No results found for query: Social Determinants of Health" in the console logs of the docker compose file when we attempt to load up the value sets for SDoH. I don't think this is a problem with how we're querying for value sets, which makes me inclined to agree that we'll need to add/modify migrations to hard code similar values like we did for newborn screening.
